### ISSUE TITLE
如何在 digitalocean 搭建一个wordpress

### ISSUE THREAD

**Issue by jsiwa** [jsiwa/sql#17]
使用 Docker 部署 WordPress 是一种高效且方便的方法。Docker 允许你将 WordPress 及其所有依赖项打包在一个容器中，确保环境一致性并简化管理。下面是使用 Docker 部署 WordPress 的步骤：

### 前提条件
- 已安装 Docker 和 Docker Compose。
- 有一个可用的 DigitalOcean Droplet 或任何其他支持 Docker 的服务器。

### 步骤 1：安装 Docker 和 Docker Compose

如果你还没有安装 Docker 和 Docker Compose，可以通过以下命令进行安装：

```sh
# 安装 Docker
sudo apt-get update
sudo apt-get install -y docker.io

# 安装 Docker Compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

### 步骤 2：创建 Docker Compose 文件

在你的工作目录中创建一个 `docker-compose.yml` 文件，内容如下：

```yaml
version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
```

### 步骤 3：启动 Docker 容器

使用 Docker Compose 启动容器：

```sh
sudo docker-compose up -d
```

这会下载所需的 Docker 镜像并启动 WordPress 和 MySQL 容器。

### 步骤 4：访问 WordPress

在浏览器中访问你的服务器 IP 地址，例如 `http://your_droplet_ip`，你将看到 WordPress 安装页面。按照提示完成安装。

### 资源消耗

使用 Docker 部署 WordPress 通常不会显著增加资源消耗，具体情况取决于你的服务器配置和负载情况。以下是一些优化建议：

1. **优化容器资源使用**：在 `docker-compose.yml` 中设置资源限制，例如 CPU 和内存限制。
   ```yaml
   wordpress:
     ...
     deploy:
       resources:
         limits:
           cpus: '0.50'
           memory: '512M'
   db:
     ...
     deploy:
       resources:
         limits:
           cpus: '0.50'
           memory: '512M'
   ```

2. **定期监控**：使用 Docker 的监控工具，如 `docker stats`，定期检查容器的资源使用情况。

3. **清理未使用的容器和镜像**：定期清理不再使用的 Docker 容器和镜像，以释放资源。
   ```sh
   sudo docker system prune -a
   ```

通过这些步骤，你可以高效地使用 Docker 在 DigitalOcean 上部署 WordPress，同时保持资源使用的可控性。Docker 的好处在于其便捷的管理和环境一致性，适合各种规模的应用部署。
